/****** Object:  Table [dbo].[APOSTA]    Script Date: 09/03/2020 12:19:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APOSTA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Status] [int] NOT NULL,
	[IdJogo] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[DataHora] [datetime] NOT NULL,
	[PlacarMandanteApostado] [int] NOT NULL,
	[PlacarVisitanteApostado] [int] NOT NULL,
	[PlacarMandanteReal] [int] NULL,
	[PlacarVisitanteReal] [int] NULL,
	[ResultadoApostado] [varchar](10) NOT NULL,
	[ResultadoReal] [varchar](10) NULL,
	[Pontos] [int] NOT NULL,
 CONSTRAINT [PK_APOSTA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APOSTA]  WITH CHECK ADD  CONSTRAINT [FK_APOSTA_USUARIO] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[USUARIO] ([Id])
GO

ALTER TABLE [dbo].[APOSTA] CHECK CONSTRAINT [FK_APOSTA_USUARIO]
GO


ALTER TABLE [dbo].[APOSTA]  WITH CHECK ADD  CONSTRAINT [FK_APOSTA_JOGO] FOREIGN KEY([IdJogo])
REFERENCES [dbo].[JOGO] ([Id])
GO

ALTER TABLE [dbo].[APOSTA] CHECK CONSTRAINT [FK_APOSTA_JOGO]
GO

