/****** Object:  Table [dbo].[BOLAO]    Script Date: 09/03/2020 12:19:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOLAO](
	[Id] [int] IDENTITY(1,3) NOT NULL,
	[Nome] [varchar](20) NOT NULL,
	[IdCriador] [int] NOT NULL,
	[IdCampeonato] [int] NOT NULL,
	[Privacidade] [int] NOT NULL,
 CONSTRAINT [PK_BOLAO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BOLAO]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_CAMPEONATO] FOREIGN KEY([IdCampeonato])
REFERENCES [dbo].[CAMPEONATO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO] CHECK CONSTRAINT [FK_BOLAO_CAMPEONATO]
GO

ALTER TABLE [dbo].[BOLAO]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_USUARIO] FOREIGN KEY([IdCriador])
REFERENCES [dbo].[USUARIO] ([ID])
GO

ALTER TABLE [dbo].[BOLAO] CHECK CONSTRAINT [FK_BOLAO_USUARIO]
GO


