/****** Object:  Table [dbo].[BOLAO_CONVITE]    Script Date: 09/03/2020 12:19:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOLAO_CONVITE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdBolao] [int] NOT NULL,
	[IdUsuarioEnvio] [int] NOT NULL,
	[IdUsuarioConvidado] [int] NOT NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_BOLAO_CONVITE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BOLAO_CONVITE]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_CONVITE_BOLAO] FOREIGN KEY([IdBolao])
REFERENCES [dbo].[BOLAO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO_CONVITE] CHECK CONSTRAINT [FK_BOLAO_CONVITE_BOLAO]
GO

ALTER TABLE [dbo].[BOLAO_CONVITE]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_CONVITE_USUARIO] FOREIGN KEY([IdUsuarioEnvio])
REFERENCES [dbo].[USUARIO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO_CONVITE] CHECK CONSTRAINT [FK_BOLAO_CONVITE_USUARIO]
GO

ALTER TABLE [dbo].[BOLAO_CONVITE]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_CONVITE_USUARIO1] FOREIGN KEY([IdUsuarioConvidado])
REFERENCES [dbo].[USUARIO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO_CONVITE] CHECK CONSTRAINT [FK_BOLAO_CONVITE_USUARIO1]
GO


