/****** Object:  Table [dbo].[BOLAO_USUARIO]    Script Date: 09/03/2020 12:19:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOLAO_USUARIO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdBolao] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
 CONSTRAINT [PK_BOLAO_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BOLAO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_USUARIO_BOLAO] FOREIGN KEY([IdBolao])
REFERENCES [dbo].[BOLAO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO_USUARIO] CHECK CONSTRAINT [FK_BOLAO_USUARIO_BOLAO]
GO

ALTER TABLE [dbo].[BOLAO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_BOLAO_USUARIO_USUARIO] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[USUARIO] ([Id])
GO

ALTER TABLE [dbo].[BOLAO_USUARIO] CHECK CONSTRAINT [FK_BOLAO_USUARIO_USUARIO]
GO


