/****** Object:  Table [dbo].[CONFIGURACAO]    Script Date: 09/03/2020 12:19:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONFIGURACAO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PontosResultado] [int] NOT NULL,
	[PontosPlacar] [int] NOT NULL,
 CONSTRAINT [PK_CONFIGURACAO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


