SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PALPITE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdJogo] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[DataHora] [datetime] NOT NULL,
	[PlacarMandantePalpite] [int] NOT NULL,
	[PlacarVisitantePalpite] [int] NOT NULL,
	[Pontos] [int] NOT NULL,
	[Finalizado] [bit] NOT NULL,
 CONSTRAINT [PK_APOSTA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PALPITE]  WITH CHECK ADD  CONSTRAINT [FK_PALPITE_USUARIO] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[USUARIO] ([Id])
GO

ALTER TABLE [dbo].[PALPITE] CHECK CONSTRAINT [FK_PALPITE_USUARIO]
GO


ALTER TABLE [dbo].[PALPITE]  WITH CHECK ADD  CONSTRAINT [FK_PALPITE_JOGO] FOREIGN KEY([IdJogo])
REFERENCES [dbo].[JOGO] ([Id])
GO

ALTER TABLE [dbo].[PALPITE] CHECK CONSTRAINT [FK_PALPITE_JOGO]
GO

